README.md

The example calls are incorrectly named.

Removed 's' from client.lists calls

---

mailchimp3/entities/report.py
mailchimp3/mailchimpclient.py

Added ability to pass in query parameters for GET requests, to support 'count' and 'offset' in mailchimpclient by converting kwargs into query parameters and adding them to the URL for GET requests.
Also added pass-through for kwargs for reports - if this is acceptable, the same could be done for the other entities.

Support for query parameters

---

mailchimp3/entities/campaign.py
mailchimp3/entities/member.py

The Mailchimp API often accepts optional GET arguments in a call - I've tweaked your code to allow these to be passed. It covers the specific endpoints where I required that functionality!

Handle passing of GET args.

---

mailchimp3/entities/campaign.py

Feedback.all() was being called as if it was a class method in the feedback() of Campaign, instead now an instance of Feedback is instantiated and the method is called on that.

Fix to feedback method on campaign API

---

mailchimp3/entities/authorizedapp.py
mailchimp3/entities/automation.py
mailchimp3/entities/automationemail.py
mailchimp3/entities/automationemailqueue.py
mailchimp3/entities/automationeremovedsubscriber.py
mailchimp3/entities/campaign.py
mailchimp3/entities/category.py
mailchimp3/entities/client.py
mailchimp3/entities/conversation.py
mailchimp3/entities/feedback.py
mailchimp3/entities/files.py
mailchimp3/entities/folder.py
mailchimp3/entities/goal.py
mailchimp3/entities/growth.py
mailchimp3/entities/interest.py
mailchimp3/entities/list.py
mailchimp3/entities/listabuse.py
mailchimp3/entities/listactivity.py
mailchimp3/entities/member.py
mailchimp3/entities/memberactivity.py
mailchimp3/entities/message.py
mailchimp3/entities/report.py
mailchimp3/entities/reportabuse.py
mailchimp3/entities/reportactivity.py
mailchimp3/entities/root.py
mailchimp3/entities/template.py
mailchimp3/mailchimpclient.py

Fix an error on Python 2.x when attempting to `urljoin` base_url with a unicode URL.`
Traceback takes the form:
```
Traceback (most recent call last):
<snipped>
File "VIRTUAL_ENV/local/lib/python2.7/site-packages/mailchimp3/mailchimpclient.py", line 49, in _get
url = urljoin(self.base_url, url)
File "VIRTUAL_ENV/local/lib/python2.7/site-packages/future/backports/urllib/parse.py", line 418, in urljoin
base, url, _coerce_result = _coerce_args(base, url)
File "VIRTUAL_ENV/local/lib/python2.7/site-packages/future/backports/urllib/parse.py", line 115, in _coerce_args
raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
```

Use unicode_literals

---

mailchimp3/entities/list.py

Enable passing kwargs to the `entities.list.all` method.
The API limits the returned results, just like by querying `members`, so one needs to be able to pass the `offset` and count `parameters`.

Add kwargs to list.all method

---

README.md
README.rst
mailchimp3/mailchimpclient.py

* If client is not enabled all API calls return None vs raising and exception
* Allows us to enable/disable easily with configuration management (chef, docker/etcd, yaml, whatever) without writing a bunch of conditionals in Python
My use case:
```python
from mailchimp3 import MailChimp
import config
client = MailChimp(config.mailchimp_user, config.mailchimp_secret, 
enabled=config.mailchimp_enabled)
def subscribe(user):
return client.member.create(list_id, data=user)
...
mailchimp_integration.subscribe(user)
...

Adding optional `enabled` flag to MailChimpClient

---

mailchimp3/helpers.py

ascii_bytes.encode() is a no-op on Python 2.

Pass a bytestring to hashlib.md5.

---

mailchimp3/entities/reportactivity.py

Parameter is campaign_id not list_id, see http://developer.mailchimp.com/documentation/mailchimp/reference/reports/email-activity/#read-get_reports_campaign_id_email_activity

Minor correction to email-activity parameters

---

mailchimp3/entities/lists.py

- Add list_id to end of url
Fixes Issue #66

Fix incorrect endpoint url for lists.update_members

---

mailchimp3/entities/listgrowthhistory.py
mailchimp3/entities/listinterestcategoryinterest.py

There were two missing return statements making
```client.lists.interest_categories.interests.all```
and
```client.lists.growth_history.all```
return nothing with ```get_all=True``` set.

Add missing return statements

---

mailchimp3/entities/campaignactions.py

This is a correction for the issue raised in #86

Correct data parsing for Campaign schedule action

---

mailchimp3/mailchimpclient.py

mailchimp3's format isn't compatible with python2.6.
```
File "/usr/lib/python2.6/site-packages/mailchimp3/__init__.py", line 97, in __init__
super(MailChimp, self).__init__(*args, **kwargs)
File "/usr/lib/python2.6/site-packages/mailchimp3/mailchimpclient.py", line 51, in __init__
self.base_url = 'https://{}.api.mailchimp.com/3.0/'.format(datacenter)
ValueError: zero length field name in format
```

python2.6 bug ValueError: zero length field name in format

---

mailchimp3/helpers.py

This closes https://github.com/charlesthk/python-mailchimp/issues/116, although I have discovered that Mailchimp itself doesn't support unicode in the prefix of emails (http://kb.mailchimp.com/accounts/management/international-characters-in-mailchimp).

Validate emails by simply checking for @.

---

mailchimp3/entities/batches.py

I spoke with the MailChimp API team over the weekend, due to the strangeness of the apparent lack of support for DELETE in the batches API. Turns out that they do support batched DELETEs; it's just that their docs are out of date. You can test this by posting the following directly to the batches API:
```
{
"operations": [
{
"method": "DELETE",
"path": "/lists/<list_id>/members/<subscriber_hash>"
}
]
}
```
The person I spoke with assures me that the developers have been notified that they should update the API docs. Though I don't know how long that will take to propagate to the [live docs page](http://developer.mailchimp.com/documentation/mailchimp/reference/batches/).
My project needs this feature pretty urgently, so I would very much appreciate this PR being integrated into a new PyPI …

Updated the batches code to allow DELETE.

---

mailchimp3/baseapi.py

This fixes a unicode-compatibility error we encountered trying to use the mailchimp3 API wrapper in a Python2/3 codebase with the [python-future library](http://python-future.org) for compatibility. 
You can reproduce this error by running the following under Python 2:
```python
from __future__ import unicode_literals
from future import standard_library
standard_library.install_aliases()
from mailchimp3 import MailChimp
mc = MailChimp('username', 'apikey')
data = {
'email_address' : 'email@example.com',
'status' : 'subscribed',
'ip_opt' : '127.0.0.1',
'timestamp_opt': '2017-04-11T17:04:03.456642+00:00',
'interests' : { 'group1' : True, 'group2': True },
}
response = mc.lists.members.create(list_id='12345', data=data)
```
This triggers the following error:
```
Traceback (most recent call …
```

BaseAPI unicode-compatibility fix

---

README.md
README.rst
mailchimp3/mailchimpclient.py

It was possible that network requests would hang indefinetly and crash our app when using MailChimpClient. We were using it in a Celery task, and that task would then hang indefinetly.
Even Celery's documentation warns against using the requests library without specifying a timeout.
```
Warning
A task that blocks indefinitely may eventually stop the worker instance from doing any other work.
If you task does I/O then make sure you add timeouts to these operations, like adding a timeout to a web request using the requests library:
connect_timeout, read_timeout = 5.0, 30.0
response = requests.get(URL, timeout=(connect_timeout, read_timeout))
Time limits are convenient for making sure all tasks return in a timely manner, but a time limit event will actually kill the process by force so only …
```

Add timeout parameter to MailChimpClient

---

mailchimp3/entities/campaignactions.py

When verifying if the schedule time of an scheduled campaign is in UTC, the utcoffset() function was missing an argument. With None as an argument it correctly compares the offset of schedule_time to the UTC time zone. Tested with Python27 and Python36-32. Doc: https://docs.python.org/2/library/datetime.html#datetime.tzinfo.utcoffset

Fixed missing argument in utcoffset() function

---

mailchimp3/entities/listmembers.py

The docs says the `status` and `status_if_new` can take 5 values, while only 4 are possible in this library (missing the `"transactional"`)
http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#edit-put_lists_list_id_members_subscriber_hash

Add missing status value for adding members to list

---

README.md
README.rst
mailchimp3/entities/automations.py
setup.py

This addresses #140 and also bumps up the minor version.
Tested with mailchimp API. See logs below.
```bash
$ mkvirtualenv test-mailchimp3
(test-mailchimp3) $ python setup.py install 
running install
...
Installed /Users/ye/.envs/test-mailchimp3/lib/python3.6/site-packages/chardet-3.0.4-py3.6.egg
Finished processing dependencies for mailchimp3==2.0.14
(test-mailchimp3) $ pip install ipython
(test-mailchimp3) $ ipython
Python 3.6.1 (default, Apr  4 2017, 09:40:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: from mailchimp3 import MailChimp
In [2]: client = MailChimp('', 'XXXXXXXXXXXXX-us1')
In [3]: client.automations.get('xxxxxxxxxx', fields='emails_sent')
Out[3]: {'emails_sent': 16}
In [4]: …
```

Add query string params for automation single workflow endpoint

---

README.md
README.rst
mailchimp3/entities/automationemails.py
setup.py

This should address majority of the issues in #143 and also bump up minor version to 2.0.15.
Verified `get_all` and `fields` filter query params with our live mailchimp account which has 37 automation workflow email campaigns, which previously only returns 10 items even though `total_items` indicates there are more than 10 email campaigns available.
```python
In [1]: import mailchimp3
In [2]: mc = mailchimp3.MailChimp('', 'xxxxxxxx-us1')
In [3]: mc.automations.emails.all('WORKFLOW_ID', get_all=True, exclude_fields='emails,_links')
Out[3]: {'total_items': 37}
In [4]: mc.automations.emails.all('WORKFLOW_ID', get_all=True, fields='emails.settings.title,total_items')
Out[4]: 
{'emails': [{'settings': {'title': 'Week 5'}},
{'settings': {'title': 'Week 11'}},
{'settings': {'title': 'Week 29'}}, …
```

Add query params (get_all, fields, exclude_fields) for Automations Workflow Emails Get All endpoint

---

mailchimp3/entities/lists.py

In the data examples in the comments for the lists, permission_reminder was mispelt.
This has been fixed across the file.

Fixed typos

---

README.md
README.rst
mailchimp3/mailchimpclient.py
setup.py

this PR adds a generic _make_requests method to capture logging on all client requests/responses
```python
import logging
logger = logging.getLogger('mailchimp3.client')
logger.addHandler(some_log_file)
```

add mailchimp3.client logging

---

mailchimp3/__init__.py
mailchimp3/entities/listmembertags.py

This PR adds support for lists.members.tags so you can manage tags for a particular list member.  Nothing really fancy but I couldn't see anything related in the code so I added this capability.

Add support for Tags

---

README.md
README.rst
mailchimp3/mailchimpclient.py
setup.py

I am getting `JSONDecodeError` messages when receiving a 504 response in `def _get` [here](https://github.com/VingtCinq/python-mailchimp/blob/master/mailchimp3/mailchimpclient.py#L163) similar to #167. This implements the same fix that is in 3377ea9 and 95f1edc for other requests.

Similar request error handling fix to #167 for remaining requests

---

README.md
README.rst
mailchimp3/baseapi.py
setup.py

As mentioned in https://github.com/VingtCinq/python-mailchimp/pull/207, sometimes using `count=1000` leads to `504 - gateway timeout` errors when hitting an api endpoint. Mailchimp support suggests using a lower count number when you start to receive these errors. Unfortunately, count is hardcoded to 1000 and cannot be changed when using `get_all=True`.
This patch modifies the default behavior such that when `get_all=True`, a user-supplied `count` is used. If `count` is not supplied by the call, then it defaults to 1000.

Remove hardcoded 1000 count for BaseApi._iterate

---

README.md
README.rst
mailchimp3/mailchimpclient.py
setup.py

This update removes the response text from the logging action taken by the logger after a request is made to prevent runaway log file sizes. I have seen that recording the raw response text on certain large queries can cause log files to very quickly become massive and fill server drives, an obvious bad problem. We might want to add a note near the top of the README files that recommends that everyone update to 3.0.10+ due to this potential issue, but I will leave that as a suggestion instead of adding it to the README at the start of this update.

Remove logging of raw responses

---

mailchimp3/entities/storepromorules.py
setup.py

I was getting an error using `client.stores.promo_rules.all(store_id=store_id, get_all=False, **{"count": 1})` and after investigating I found a typo in the path appendix for `promo_rules.all`.
Hope that helps! Thanks for the great library.

Fix wrong path for getting all promo-rules

---

mailchimp3/entities/campaigns.py

In campaign creation endpoint :
- remove
- settings as a required parameter
- settings.from_name as a required parameter
- settings.subject_line as a required parameter
- settings.reply_to as a required parameter
- add a check if type is variate to ensure 
- settings.subject_lines or variate_settings.subject_line is populated
- settings.from_name or variate_settings.from_names is populated
- settings.reply_to or variate_settings.reply_to_addresses is populated

fix required fields on campaign creation

---

mailchimp3/entities/listmemberactivity.py

Can get more than 50 events as compared to activity.all and a lot more information as well.

Add activity-feed endpoint in listmemberactivity
