VingtCinq/python-mailchimp

- mailchimp3/entities/automationeremovedsubscriber.py
- mailchimp3/mailchimpclient.py
As per subject line - spotted an incorrect arg name on a couple of methods.
> Fixed incorrect arg name.

- mailchimp3/__init__.py
- mailchimp3/entities/authorizedapp.py
- mailchimp3/entities/automation.py
- mailchimp3/entities/automationemail.py
- mailchimp3/entities/automationemailqueue.py
- mailchimp3/entities/automationeremovedsubscriber.py
- mailchimp3/entities/campaign.py
- mailchimp3/entities/category.py
- mailchimp3/entities/client.py
- mailchimp3/entities/conversation.py
- mailchimp3/entities/feedback.py
- mailchimp3/entities/files.py
- mailchimp3/entities/folder.py
- mailchimp3/entities/goal.py
- mailchimp3/entities/growth.py
- mailchimp3/entities/interest.py
- mailchimp3/entities/list.py
- mailchimp3/entities/listabuse.py
- mailchimp3/entities/listactivity.py
- mailchimp3/entities/member.py
- mailchimp3/entities/memberactivity.py
- mailchimp3/entities/message.py
- mailchimp3/entities/report.py
- mailchimp3/entities/reportabuse.py
- mailchimp3/entities/reportactivity.py
- mailchimp3/entities/template.py
- mailchimp3/mailchimpclient.py
- test.py
Various changes to the project to make it work with Python 3.
> Python 3 compatibility

- mailchimp3/mailchimpclient.py
When Mailchimp API returns an HTTP error code: I've found it useful to add the exception the content of the response sent by Mailchimp - it often contains a detailed error message.
> Better handling of error messages returned by the Mailchimp API.

- mailchimp3/__init__.py
- mailchimp3/entities/batches.py
- mailchimp3/helpers.py
- mailchimp3/mailchimpclient.py
Hi, thanks for contributions to the open source. I've implemented batch operations. [http://developer.mailchimp.com/documentation/mailchimp/guides/how-to-use-batch-operations/](Mailchimp Batch Operations)
Hope it's helpful.
> Added batch operations

- mailchimp3/entities/campaign.py
Adds 2 crucial methods for creating and sending campaigns using v3 of the mailchimp api
> Added methods for creating and sending campaigns

- README.md
- README.rst
- mailchimp3/entities/interest.py
- setup.py
Updates required in addition to those in my previous pull request (thanks for responding so quickly).
Hope you don't mind but I bumped the version number in the hope that you'd consider getting an updated version of the codebase onto pypi.
Please let me know if there's anything I can do to assist.
> Allows url params to be passed to interest.all method

- mailchimp3/entities/campaign.py
- setup.py
Created a method for campaign patch and cancel-send
> Added campaign patch and cancel-send endpoints

- README.md
- mailchimp3/__init__.py
- mailchimp3/entities/root.py
- mailchimp3/mailchimpclient.py
- setup.py
I added a Root class, for the root endpoint, which gives information about user account. Also I have fixed a bug on PUT request. Mailchimp returns 204 for some PUT requests, and this was causing 2 errors:
1-) It always raised HTTPError when response was 204.
2-) r.json() caused error since 204 has no message. It now returns {'status' :204}
> Added Root class for account info, and fixed a bug on the PUT response treatment.

- mailchimp3/__init__.py
- mailchimp3/entities/campaign.py
- mailchimp3/entities/folder.py
This connects in the existing Folder entity into the main class and adds the missing create function.
> This fixes #27 in the original python-mailchimp project

- mailchimp3/entities/member.py
- mailchimp3/mailchimpclient.py
I have added support for create_or_update member to a list as documented in the open issue by @aaugustin https://github.com/charlesthk/python-mailchimp/issues/24
> Enables to add or update a list member

- mailchimp3/__init__.py
- mailchimp3/entities/category.py
- mailchimp3/entities/list.py
- mailchimp3/entities/mergefields.py
- setup.py
This pull requests handles the merge-fields api  and adds homaralex commit of pagination in list.all() listing
> Support for Merge-Fields of Lists

- mailchimp3/mailchimpclient.py
I changed how HTTPError is raised according to my suggestion in #33
> raise HTTPError using API response directly

- mailchimp3/__init__.py
- mailchimp3/baseapi.py
- mailchimp3/entities/segments.py
Copied from mergefields.py. Seems to be working fine. I also fixed a bug that also affects merge fields.
> Add support for segments

- README.md
- README.rst
- mailchimp3/baseapi.py
- mailchimp3/helpers.py
Referencing the issue: https://github.com/charlesthk/python-mailchimp/issues/59
Does not affect the issue of non-inclusion of `"total_items"` in entity `all` methods.
> Partial fixes for issues raised in #59

- mailchimp3/entities/automationemailqueues.py
- mailchimp3/entities/campaignfeedback.py
- mailchimp3/entities/campaignfolders.py
- mailchimp3/entities/campaigns.py
- mailchimp3/entities/conversationmessages.py
- mailchimp3/entities/filemanagerfiles.py
- mailchimp3/entities/filemanagerfolders.py
- mailchimp3/entities/listinterestcategories.py
- mailchimp3/entities/listinterestcategoryinterest.py
- mailchimp3/entities/listmembernotes.py
- mailchimp3/entities/listmembers.py
- mailchimp3/entities/listmergefields.py
- mailchimp3/entities/lists.py
- mailchimp3/entities/listsegmentmembers.py
- mailchimp3/entities/listsegments.py
- mailchimp3/entities/listtwitterleadgenerationcards.py
- mailchimp3/entities/listwebhooks.py
- mailchimp3/entities/storecartlines.py
- mailchimp3/entities/storecarts.py
- mailchimp3/entities/storecustomers.py
- mailchimp3/entities/storeorderlines.py
- mailchimp3/entities/storeorders.py
- mailchimp3/entities/storeproducts.py
- mailchimp3/entities/storeproductvariants.py
- mailchimp3/entities/stores.py
- mailchimp3/entities/templatefolders.py
- mailchimp3/entities/templates.py
This should resolve the issue of running a create-style operation while using the noop function and prevent that from returning an error.
> Add checks to properly handle the use of noop

- mailchimp3/entities/campaigns.py
Fix for error mentioned in #56 pending verification
> Fix for issue 56

- README.md
- README.rst
> Properly format Mailchimp API structure in README

- mailchimp3/mailchimpclient.py
Resolution for issue #75 that was pointed out as those endpoints return a 204 empty response on success.
> Return None when status code is 204 for no content

- mailchimp3/entities/listmergefields.py
> list merge field create returns a data with 'merge_id'

- README.md
- README.rst
- mailchimp3/entities/templatedefaultcontent.py
- setup.py
The endpoint was incorrectly listed as reports instead of templates
This resolves the issue pointed out in #101
> Fix incorrect endpoint

- README.rst
- mailchimp3/entities/storeproducts.py
Add the `update` method for stores products.
> Add StoreProducts update method

- README.md
- README.rst
- setup.py
> Update version number for PR 135

- README.md
- README.rst
- mailchimp3/entities/storeproductvariants.py
- setup.py
* Update all() and get() to use GET instead of POST
* Version number to 2.0.17
> Fix issue with product variant endpoints

- README.md
- README.rst
- mailchimp3/mailchimpclient.py
- setup.py
As recommended by MailChimp API Best Practices, and singer.io best practices.
> Add support for custom headers

- mailchimp3/entities/automationemailactions.py
- mailchimp3/entities/campaigns.py
- mailchimp3/entities/ping.py
- mailchimp3/entities/reportgoogleanalytics.py
- mailchimp3/entities/reportopendetails.py
- mailchimp3/entities/storepromocodes.py
- mailchimp3/entities/storepromorules.py
https://github.com/charlesthk/python-mailchimp/issues/158
I did the following:
Add DELETE method to /automations/{workflow_id}/emails/{workflow_email_id}
Add new endpoint for Campaign Open Reports
Add new endpoint for Google Analytics
Add new endpoint for Ping
Add new endpoints for E-Commerce Promo Rules and E-Commerce Promo Codes
> Closes Issue #158

- README.rst
- mailchimp3/entities/listmembers.py
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#action-post_lists_list_id_members_subscriber_hash_actions_delete_permanent
> Add members list actions delete-permanent

- README.md
- README.rst
- mailchimp3/mailchimpclient.py
- setup.py
I noticed that same issue as described in #167 but this time for a PUT call. I applied the same fix as commit 3377ea982d6b541fa61ff55dfea42643598a27de
> Similar to fix #167 but for PUT call

- README.md
- README.rst
- mailchimp3/__init__.py
- mailchimp3/entities/landingepagecontent.py
- mailchimp3/entities/landingpageaction.py
- mailchimp3/entities/landingpagecontent.py
- mailchimp3/entities/landingpages.py
- setup.py
This branch adds the landing pages endpoint to the mailchimp client.
>  Add Landing Pages endpoints (content, actions)

- README.md
- README.rst
- mailchimp3/baseapi.py
- setup.py
If the enabled flag is False and an endpoint uses iterate, it will fail, this fixes that by immediately returning if the enabled flag is False
> Update iterate to respect enabled flag

- README.md
- README.rst
- mailchimp3/__init__.py
- mailchimp3/entities/customerjourney.py
- setup.py
Noticed this bit of documentation in the mailchimp API that isn't supported by this package.
https://mailchimp.com/developer/marketing/api/customer-journeys-journeys-steps-actions/
Should be fairly self explanatory
> Customer journeys API implementation
